#!/bin/sh

set -euo pipefail

export VERCEL_PROTECTION_BYPASS_TOKEN=${VERCEL_PROTECTION_BYPASS_TOKEN:-${VERCEL_PROTECTION_BYPASS_TOKEN%:*}}
export VERCEL_JWT=${VERCEL_JWT:-${VERCEL_JWT%:*}}
export BACKEND_DOMAIN=${BACKEND_DOMAIN:-${BACKEND_HOST%:*}}
export BACKEND_DOMAIN=${BACKEND_DOMAIN:-${BACKEND_HOST%:*}}
export BACKEND_PORT=${BACKEND_PORT:-${BACKEND_HOST##*:}}

BACKEND_DOMAIN=${BACKEND_DOMAIN##*://}

echo using backend: ${BACKEND_DOMAIN} with port: ${BACKEND_PORT}

exec caddy run --config Caddyfile --adapter caddyfile 2>&1
